version: '3.8'
services:
  api:
    image: timalander/garmin-gpt-summary:latest
    environment:
      - OPENAI_API_KEY
      - MAILGUN_API_KEY
      - GARMIN_SUMMARY_DB_PATH
      - TO_EMAIL
      - FROM_EMAIL
      - FROM_EMAIL_DOMAIN
    ports:
      - '8020:8020'
    networks:
      - default
    volumes:
      - /volume1/docker/garmin_data:/data

networks:
  default:
    driver: bridge
